### ISSUE TITLE
[Docker] Add Docker support

### ISSUE THREAD

**Issue by benjaminch** [mtharrison/wasmbooth#2]
Hello !

First, I wanted to thank you for this project, it's really awesome ! I am working on learning RUST and apply it to WASM and this project is awesome I I would be happy to start to contribute to it in the next future :)

My first humble contribution if you are okay with it will be to add Docker support to easily be able to deploy it (I am using Kubernetes).

I will push a PR to add this support, please let me know what you think ! :)

Cheers !

**Comment by benjaminch** [comment]
Hey @mtharrison, I was wondering if you had time to look at this one and if it makes sense to you?
Thanks :)

**Comment by mtharrison** [comment]
https://github.com/mtharrison/wasmbooth/pull/3
